import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppProvider from "./provider";
import { NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const runtime = "edge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={`${inter.className} antialiased`}>
        <NextIntlClientProvider>
          <AppProvider>
            <main>{children}</main>
          </AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
